// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeBoard.Data;

#nullable disable

namespace RecipeBoard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260829143435_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RecipeBoard.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Breakfast"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Lunch"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Dinner"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Dessert"
                        });
                });

            modelBuilder.Entity("RecipeBoard.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RecipeId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            CategoryId = 1,
                            Instructions = "Mix flour, milk, and eggs. Cook on a griddle until golden on both sides.",
                            PrepTimeMinutes = 20,
                            Title = "Pancakes"
                        },
                        new
                        {
                            RecipeId = 2,
                            CategoryId = 2,
                            Instructions = "Butter two slices of bread, add cheese, and grill until golden.",
                            PrepTimeMinutes = 10,
                            Title = "Grilled Cheese Sandwich"
                        },
                        new
                        {
                            RecipeId = 3,
                            CategoryId = 3,
                            Instructions = "Cook pasta. Brown ground beef with onions and garlic, add tomato sauce, simmer, and combine.",
                            PrepTimeMinutes = 40,
                            Title = "Spaghetti Bolognese"
                        },
                        new
                        {
                            RecipeId = 4,
                            CategoryId = 4,
                            Instructions = "Cream butter and sugar, add eggs and vanilla, mix in flour and chocolate chips, bake at 350F for 10 minutes.",
                            PrepTimeMinutes = 30,
                            Title = "Chocolate Chip Cookies"
                        });
                });

            modelBuilder.Entity("RecipeBoard.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Password = "guest123",
                            Role = "User",
                            Username = "guest"
                        });
                });

            modelBuilder.Entity("RecipeBoard.Models.Recipe", b =>
                {
                    b.HasOne("RecipeBoard.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
